# NUMPY TUTORIAL

### Load in Numpy

In [2]:
import numpy as np

### The Basics

In [3]:
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get dimension
b.ndim

2

In [6]:
# Get shape
b.shape

(2, 3)

In [7]:
# Get Type
a.dtype

dtype('int32')

In [8]:
# Get Size
a.nbytes

12

### Accessing/Changing specific elements, rows, columns, etc

In [9]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specific element [r, c]
a[1, 5]

13

In [11]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [13]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [14]:
a[1, 5] = 20
print(a)

a[:, 2] = [1, 2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### 3D example

In [15]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
# Get specific element (work outside in)
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [17]:
# Replace
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [18]:
# All 0s matrix
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [20]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [21]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.70758225, 0.98099029],
       [0.81185738, 0.87502906],
       [0.73309561, 0.35925394],
       [0.93962683, 0.49695189]])

In [23]:
# Random Integer values
np.random.randint(-4, 8, size=(3, 3))

array([[ 3,  5,  7],
       [ 5,  1, -3],
       [ 5, -1,  3]])

In [24]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Problem 1: How do you initialize this array?

In [26]:
# Array
array = np.array([[1, 1, 1, 1, 1],
                  [1, 0, 0, 0, 1],
                  [1, 0, 9, 0, 1],
                  [1, 0, 0, 0, 1],
                  [1, 1, 1, 1, 1]])
array

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [27]:
# Initializing with methods
output = np.ones([5, 5], dtype='int32')
z = np.zeros((3, 3))
z[1, 1] = 9
output[1:-1, 1:-1] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


##### Be careful when copying arrays!!!

In [28]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

print(b)
print(a)

[100   2   3]
[1 2 3]


### Mathematics

In [29]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [34]:
a + 2

array([1, 2, 3, 4])

In [31]:
a - 2

array([-1,  0,  1,  2])

In [32]:
a * 2

array([2, 4, 6, 8])

In [33]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [35]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [36]:
a ** 2

array([ 1,  4,  9, 16])

In [37]:
# Take the sin
np.sin(a)

# For a

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [38]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

#### Linear Algebra

In [44]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [47]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [48]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

#### Statistics

In [49]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.min(stats)

array([1, 4])

In [55]:
np.max(stats, axis=1)

array([3, 6])

In [57]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [60]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [63]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [65]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

#### Load Data from File

In [71]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

#### Boolean Masking and Advanced indexing

In [72]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [74]:
# You can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [80]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

### Problem 2: How do you index these values?

In [101]:
# Array
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25],
                  [26, 27, 28, 29, 30]])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [84]:
# Question 1
array[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [98]:
# Question 2
array[[0, 1, 2, 3], [1, 2, 3, 4]]

In [102]:
# Question 3
a = array[ [0, 4, 5], 3:]
print(a)

[[ 4  5]
 [24 25]
 [29 30]]
